const { contextBridge, ipcRenderer } = require("electron");
const fs = require("fs");
const path = require("path");

contextBridge.exposeInMainWorld("electronAPI", {
  toIpcMain: (channel, args) => {
    console.log("[IPC] renderer to main", { channel, ...args });
    return ipcRenderer.invoke("main-listen", { channel, ...args });
  },

  onIpcRenderer: (callback) => {
    return ipcRenderer.on("renderer-listen", (event, ...args) => {
      console.log("[IPC] main to renderer", args);
      const { channel, ..._args } = args[0];
      return callback(channel, _args);
    });
  },
  preload: path.resolve(__dirname, "./preload.js"),
  mock: path.resolve(__dirname, "./mock.js"),
  getMockApiList: function () {
    const mockApiList = [
      {
        template: "/recommend_api/v1/article/recommend_all_feed",
        responseData: {
          err_no: 0,
          err_msg: "success",
          data: [
            {
              item_type: 2,
              item_info: {
                article_id: "7231577806189133884",
                article_info: {
                  article_id: "7231577806189133884",
                  user_id: "3526889034488174",
                  category_id: "6809637767543259144",
                  tag_ids: [6809640407484334093, 6809640398105870343, 6809640744349859848],
                  visible_level: 0,
                  link_url: "",
                  cover_image: "https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/d9806a499dc74e579bea24410fe9946e~tplv-k3u1fbpfcp-watermark.image?",
                  is_gfw: 0,
                  title: "偏爱console.log的你，肯定会觉得这个插件泰裤辣！23",
                  brief_content:
                    "前言 毋庸置疑，要说前端调试代码用的最多的，肯定是console.log，虽然我现在 debugger 用的比较多，但对于生产环境、小程序真机调试，还是需要用到 log 来查看变量值，比如我下午遇到个",
                  is_english: 0,
                  is_original: 1,
                  user_index: 14.187589816707584,
                  original_type: 0,
                  original_author: "",
                  content: "",
                  ctime: "1683763189",
                  mtime: "1683763203",
                  rtime: "1683763203",
                  draft_id: "7231564187255144485",
                  view_count: 26706,
                  collect_count: 453,
                  digg_count: 343,
                  comment_count: 134,
                  hot_index: 1812,
                  is_hot: 0,
                  rank_index: 0.14134918,
                  status: 2,
                  verify_status: 1,
                  audit_status: 2,
                  mark_content: "",
                  display_count: 0,
                  is_markdown: 1,
                  app_html_content: "",
                  version: 1,
                },
                author_user_info: {
                  user_id: "3526889034488174",
                  user_name: "暴走老七",
                  company: "",
                  job_title: "知乎@暴走，公众号 @暴走老七",
                  avatar_large: "https://p9-passport.byteacctimg.com/img/user-avatar/9b2d61d65abbd1b6d6d6cce35326dec4~300x300.image",
                  level: 0,
                  description: "没有自行车，难道就走不了路？",
                  followee_count: 0,
                  follower_count: 0,
                  post_article_count: 0,
                  digg_article_count: 0,
                  got_digg_count: 0,
                  got_view_count: 0,
                  post_shortmsg_count: 0,
                  digg_shortmsg_count: 0,
                  isfollowed: false,
                  favorable_author: 0,
                  power: 0,
                  study_point: 0,
                  university: {
                    university_id: "0",
                    name: "",
                    logo: "",
                  },
                  major: {
                    major_id: "0",
                    parent_id: "0",
                    name: "",
                  },
                  student_status: 0,
                  select_event_count: 0,
                  select_online_course_count: 0,
                  identity: 0,
                  is_select_annual: false,
                  select_annual_rank: 0,
                  annual_list_type: 0,
                  extraMap: {},
                  is_logout: 0,
                  annual_info: [],
                  account_amount: 0,
                  user_growth_info: {
                    user_id: 0,
                    jpower: 0,
                    jscore: 0,
                    jpower_level: 0,
                    jscore_level: 0,
                    jscore_title: "",
                    author_achievement_list: [],
                    vip_level: 0,
                    vip_title: "",
                    jscore_next_level_score: 0,
                    jscore_this_level_mini_score: 0,
                    vip_score: 0,
                  },
                  is_vip: false,
                  become_author_days: 0,
                  collection_set_article_count: 0,
                  recommend_article_count_daily: 0,
                  article_collect_count_daily: 0,
                },
                category: {
                  category_id: "0",
                  category_name: "",
                  category_url: "",
                  rank: 0,
                  back_ground: "",
                  icon: "",
                  show_type: 0,
                  item_type: 0,
                  promote_tag_cap: 0,
                  promote_priority: 0,
                },
                tags: [
                  {
                    id: 2546526,
                    tag_id: "6809640407484334093",
                    tag_name: "前端",
                    color: "#60ADFF",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/bac28828a49181c34110.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 1,
                    ctime: 1435971546,
                    mtime: 1688993283,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 389276,
                    concern_user_count: 655848,
                  },
                  {
                    id: 2546519,
                    tag_id: "6809640398105870343",
                    tag_name: "JavaScript",
                    color: "#616161",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/5d70fd6af940df373834.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1435884803,
                    mtime: 1688993283,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 130546,
                    concern_user_count: 514768,
                  },
                  {
                    id: 2546770,
                    tag_id: "6809640744349859848",
                    tag_name: "Babel",
                    color: "#000000",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/b8db05f1350a9fcbada6.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1487105648,
                    mtime: 1688974053,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 1083,
                    concern_user_count: 13189,
                  },
                ],
                user_interact: {
                  id: 7231577806189133884,
                  omitempty: 2,
                  user_id: 0,
                  is_digg: false,
                  is_follow: false,
                  is_collect: false,
                  collect_set_count: 0,
                },
                org: {
                  org_info: null,
                  is_followed: false,
                },
                req_id: "20230710205142F1EA693B02ADABADD4DB",
                status: {
                  push_status: 0,
                },
                extra: {
                  extra: "",
                },
              },
            },
            {
              item_type: 2,
              item_info: {
                article_id: "7221884988492382267",
                article_info: {
                  article_id: "7221884988492382267",
                  user_id: "289926798118589",
                  category_id: "6809637767543259144",
                  tag_ids: [6809640398105870343, 6809640375880253447, 6809640369764958215],
                  visible_level: 0,
                  link_url: "",
                  cover_image: "https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/7dbe33c61c7e4537a13989a482be7ef8~tplv-k3u1fbpfcp-watermark.image?",
                  is_gfw: 0,
                  title: "new Date() 我忍你很久了！",
                  brief_content:
                    "大家平时在开发的时候有没被new Date()折磨过？就是它的诸多怪异的设定让你每每用的时候，都可能不小心踩坑。造成程序意外出错，却一下子找不到问题出处，那叫一个烦透了…… 下面，我就列举它的“四宗罪",
                  is_english: 0,
                  is_original: 1,
                  user_index: 12.986834076923078,
                  original_type: 0,
                  original_author: "",
                  content: "",
                  ctime: "1681481899",
                  mtime: "1681543425",
                  rtime: "1681481903",
                  draft_id: "7221858081494483001",
                  view_count: 47120,
                  collect_count: 418,
                  digg_count: 370,
                  comment_count: 149,
                  hot_index: 2875,
                  is_hot: 0,
                  rank_index: 0.13966417,
                  status: 2,
                  verify_status: 1,
                  audit_status: 2,
                  mark_content: "",
                  display_count: 0,
                  is_markdown: 1,
                  app_html_content: "",
                  version: 2,
                },
                author_user_info: {
                  user_id: "289926798118589",
                  user_name: "passerby6061",
                  company: "",
                  job_title: "",
                  avatar_large: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/329405af8cd92c3d99da.jpeg~tplv-t2oaga2asx-image.image",
                  level: 0,
                  description: "",
                  followee_count: 0,
                  follower_count: 0,
                  post_article_count: 0,
                  digg_article_count: 0,
                  got_digg_count: 0,
                  got_view_count: 0,
                  post_shortmsg_count: 0,
                  digg_shortmsg_count: 0,
                  isfollowed: false,
                  favorable_author: 0,
                  power: 0,
                  study_point: 0,
                  university: {
                    university_id: "0",
                    name: "",
                    logo: "",
                  },
                  major: {
                    major_id: "0",
                    parent_id: "0",
                    name: "",
                  },
                  student_status: 0,
                  select_event_count: 0,
                  select_online_course_count: 0,
                  identity: 0,
                  is_select_annual: false,
                  select_annual_rank: 0,
                  annual_list_type: 0,
                  extraMap: {},
                  is_logout: 0,
                  annual_info: [],
                  account_amount: 0,
                  user_growth_info: {
                    user_id: 0,
                    jpower: 0,
                    jscore: 0,
                    jpower_level: 0,
                    jscore_level: 0,
                    jscore_title: "",
                    author_achievement_list: [],
                    vip_level: 0,
                    vip_title: "",
                    jscore_next_level_score: 0,
                    jscore_this_level_mini_score: 0,
                    vip_score: 0,
                  },
                  is_vip: false,
                  become_author_days: 0,
                  collection_set_article_count: 0,
                  recommend_article_count_daily: 0,
                  article_collect_count_daily: 0,
                },
                category: {
                  category_id: "0",
                  category_name: "",
                  category_url: "",
                  rank: 0,
                  back_ground: "",
                  icon: "",
                  show_type: 0,
                  item_type: 0,
                  promote_tag_cap: 0,
                  promote_priority: 0,
                },
                tags: [
                  {
                    id: 2546519,
                    tag_id: "6809640398105870343",
                    tag_name: "JavaScript",
                    color: "#616161",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/5d70fd6af940df373834.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1435884803,
                    mtime: 1688993283,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 130546,
                    concern_user_count: 514768,
                  },
                  {
                    id: 2546502,
                    tag_id: "6809640375880253447",
                    tag_name: "GitHub",
                    color: "#616161",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/0d614af263aa63aa6a77.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1432234558,
                    mtime: 1688992264,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 16646,
                    concern_user_count: 438778,
                  },
                  {
                    id: 2546498,
                    tag_id: "6809640369764958215",
                    tag_name: "Vue.js",
                    color: "",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/7b5c3eb591b671749fee.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1432234520,
                    mtime: 1688993283,
                    id_type: 9,
                    tag_alias: "vue,Vue",
                    post_article_count: 59453,
                    concern_user_count: 419994,
                  },
                ],
                user_interact: {
                  id: 7221884988492382267,
                  omitempty: 2,
                  user_id: 0,
                  is_digg: false,
                  is_follow: false,
                  is_collect: false,
                  collect_set_count: 0,
                },
                org: {
                  org_info: null,
                  is_followed: false,
                },
                req_id: "20230710205142F1EA693B02ADABADD4DB",
                status: {
                  push_status: 0,
                },
                extra: {
                  extra: "",
                },
              },
            },
            {
              item_type: 2,
              item_info: {
                article_id: "7252911555524345914",
                article_info: {
                  article_id: "7252911555524345914",
                  user_id: "2225067268010136",
                  category_id: "6809637772874219534",
                  tag_ids: [6809641083107016712],
                  visible_level: 0,
                  link_url: "",
                  cover_image: "https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/e53ad89a50af453bae99fa187271e425~tplv-k3u1fbpfcp-watermark.image?",
                  is_gfw: 0,
                  title: "上网必备！这些网站绝对是互联网宝藏！带你进入全新的在线世界",
                  brief_content:
                    "互联网上有无数的网站，有些是我们经常使用的，有些是我们不知道的。今天，我要给大家推荐一些非常有用的中国国内网站，它们可以帮助你提高工作效率、学习知识、拓展视野、娱乐生活等等。这些网站都是我从搜索结果中",
                  is_english: 0,
                  is_original: 1,
                  user_index: 7.046910913371528,
                  original_type: 0,
                  original_author: "",
                  content: "",
                  ctime: "1688717913",
                  mtime: "1688724830",
                  rtime: "1688720094",
                  draft_id: "7252954798356578359",
                  view_count: 2181,
                  collect_count: 35,
                  digg_count: 15,
                  comment_count: 0,
                  hot_index: 124,
                  is_hot: 0,
                  rank_index: 0.46334065,
                  status: 2,
                  verify_status: 1,
                  audit_status: 2,
                  mark_content: "",
                  display_count: 0,
                  is_markdown: 0,
                  app_html_content: "",
                  version: 2,
                },
                author_user_info: {
                  user_id: "2225067268010136",
                  user_name: "玄明Hanko",
                  company: "",
                  job_title: "IT",
                  avatar_large: "https://p3-passport.byteacctimg.com/img/user-avatar/10f87fc52387cf0404d6c296b52adab1~300x300.image",
                  level: 0,
                  description: "玄明Hanko(java)，从业于互联网信息安全领域及金融保险行业。专注于信息安全、电子印章/签名、流程引擎及规则引擎的开发与管理。",
                  followee_count: 0,
                  follower_count: 0,
                  post_article_count: 0,
                  digg_article_count: 0,
                  got_digg_count: 0,
                  got_view_count: 0,
                  post_shortmsg_count: 0,
                  digg_shortmsg_count: 0,
                  isfollowed: false,
                  favorable_author: 0,
                  power: 0,
                  study_point: 0,
                  university: {
                    university_id: "0",
                    name: "",
                    logo: "",
                  },
                  major: {
                    major_id: "0",
                    parent_id: "0",
                    name: "",
                  },
                  student_status: 0,
                  select_event_count: 0,
                  select_online_course_count: 0,
                  identity: 0,
                  is_select_annual: false,
                  select_annual_rank: 0,
                  annual_list_type: 0,
                  extraMap: {},
                  is_logout: 0,
                  annual_info: [],
                  account_amount: 0,
                  user_growth_info: {
                    user_id: 0,
                    jpower: 0,
                    jscore: 0,
                    jpower_level: 0,
                    jscore_level: 0,
                    jscore_title: "",
                    author_achievement_list: [],
                    vip_level: 0,
                    vip_title: "",
                    jscore_next_level_score: 0,
                    jscore_this_level_mini_score: 0,
                    vip_score: 0,
                  },
                  is_vip: false,
                  become_author_days: 0,
                  collection_set_article_count: 0,
                  recommend_article_count_daily: 0,
                  article_collect_count_daily: 0,
                },
                category: {
                  category_id: "0",
                  category_name: "",
                  category_url: "",
                  rank: 0,
                  back_ground: "",
                  icon: "",
                  show_type: 0,
                  item_type: 0,
                  promote_tag_cap: 0,
                  promote_priority: 0,
                },
                tags: [
                  {
                    id: 2547014,
                    tag_id: "6809641083107016712",
                    tag_name: "资讯",
                    color: "",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/gold-user-assets/152713444205566dc0b9fb8a213cba8cf32db3de6931b.jpg~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1514876317,
                    mtime: 1688978906,
                    id_type: 9,
                    tag_alias: "开源库资讯,发版,产品发布,新闻",
                    post_article_count: 3357,
                    concern_user_count: 5198,
                  },
                ],
                user_interact: {
                  id: 7252911555524345914,
                  omitempty: 2,
                  user_id: 0,
                  is_digg: false,
                  is_follow: false,
                  is_collect: false,
                  collect_set_count: 0,
                },
                org: {
                  org_info: null,
                  is_followed: false,
                },
                req_id: "20230710205142F1EA693B02ADABADD4DB",
                status: {
                  push_status: 0,
                },
                extra: {
                  extra: "",
                },
              },
            },
            {
              item_type: 2,
              item_info: {
                article_id: "7188894691356573754",
                article_info: {
                  article_id: "7188894691356573754",
                  user_id: "2594503172831208",
                  category_id: "6809637767543259144",
                  tag_ids: [6809640407484334093, 6809641167680962568, 6809640369764958215],
                  visible_level: 0,
                  link_url: "",
                  cover_image: "https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/baf9043e819f418f9b09bd458d05f063~tplv-k3u1fbpfcp-watermark.image?",
                  is_gfw: 0,
                  title: "前端性能优化——首页资源压缩63%、白屏时间缩短86%",
                  brief_content: "提升首屏的加载速度，是前端性能优化中最重要的环节，这里笔者梳理出一些 `常规且有效` 的首屏优化建议 通过对比优化前后的性能变化，来验证方案的有效性，了解并掌握其原理",
                  is_english: 0,
                  is_original: 1,
                  user_index: 16.79982991840145,
                  original_type: 0,
                  original_author: "",
                  content: "",
                  ctime: "1673794984",
                  mtime: "1678356983",
                  rtime: "1673795001",
                  draft_id: "7187224068548984869",
                  view_count: 90793,
                  collect_count: 5966,
                  digg_count: 2554,
                  comment_count: 143,
                  hot_index: 7236,
                  is_hot: 0,
                  rank_index: 0.14036054,
                  status: 2,
                  verify_status: 1,
                  audit_status: 2,
                  mark_content: "",
                  display_count: 0,
                  is_markdown: 1,
                  app_html_content: "",
                  version: 7,
                },
                author_user_info: {
                  user_id: "2594503172831208",
                  user_name: "海阔_天空",
                  company: "",
                  job_title: "前端开发",
                  avatar_large: "https://p3-passport.byteacctimg.com/img/user-avatar/8958f4ea986dc2f6c590a2c7a2328743~300x300.image",
                  level: 0,
                  description: "编程如逆水行舟 不进则退",
                  followee_count: 0,
                  follower_count: 0,
                  post_article_count: 0,
                  digg_article_count: 0,
                  got_digg_count: 0,
                  got_view_count: 0,
                  post_shortmsg_count: 0,
                  digg_shortmsg_count: 0,
                  isfollowed: false,
                  favorable_author: 0,
                  power: 0,
                  study_point: 0,
                  university: {
                    university_id: "0",
                    name: "",
                    logo: "",
                  },
                  major: {
                    major_id: "0",
                    parent_id: "0",
                    name: "",
                  },
                  student_status: 0,
                  select_event_count: 0,
                  select_online_course_count: 0,
                  identity: 0,
                  is_select_annual: false,
                  select_annual_rank: 0,
                  annual_list_type: 0,
                  extraMap: {},
                  is_logout: 0,
                  annual_info: [],
                  account_amount: 0,
                  user_growth_info: {
                    user_id: 0,
                    jpower: 0,
                    jscore: 0,
                    jpower_level: 0,
                    jscore_level: 0,
                    jscore_title: "",
                    author_achievement_list: [],
                    vip_level: 0,
                    vip_title: "",
                    jscore_next_level_score: 0,
                    jscore_this_level_mini_score: 0,
                    vip_score: 0,
                  },
                  is_vip: false,
                  become_author_days: 0,
                  collection_set_article_count: 0,
                  recommend_article_count_daily: 0,
                  article_collect_count_daily: 0,
                },
                category: {
                  category_id: "0",
                  category_name: "",
                  category_url: "",
                  rank: 0,
                  back_ground: "",
                  icon: "",
                  show_type: 0,
                  item_type: 0,
                  promote_tag_cap: 0,
                  promote_priority: 0,
                },
                tags: [
                  {
                    id: 2546526,
                    tag_id: "6809640407484334093",
                    tag_name: "前端",
                    color: "#60ADFF",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/bac28828a49181c34110.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 1,
                    ctime: 1435971546,
                    mtime: 1688993283,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 389276,
                    concern_user_count: 655848,
                  },
                  {
                    id: 2547076,
                    tag_id: "6809641167680962568",
                    tag_name: "性能优化",
                    color: "",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/gold-user-assets/1552374613638f172b668f237482fee67f11b7ac8c181.jpg~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1548033194,
                    mtime: 1688989189,
                    id_type: 9,
                    tag_alias: "Performance optimization",
                    post_article_count: 3997,
                    concern_user_count: 47765,
                  },
                  {
                    id: 2546498,
                    tag_id: "6809640369764958215",
                    tag_name: "Vue.js",
                    color: "",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/7b5c3eb591b671749fee.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1432234520,
                    mtime: 1688993283,
                    id_type: 9,
                    tag_alias: "vue,Vue",
                    post_article_count: 59453,
                    concern_user_count: 419994,
                  },
                ],
                user_interact: {
                  id: 7188894691356573754,
                  omitempty: 2,
                  user_id: 0,
                  is_digg: false,
                  is_follow: false,
                  is_collect: false,
                  collect_set_count: 0,
                },
                org: {
                  org_info: null,
                  is_followed: false,
                },
                req_id: "20230710205142F1EA693B02ADABADD4DB",
                status: {
                  push_status: 0,
                },
                extra: {
                  extra: "",
                },
              },
            },
            {
              item_type: 14,
              item_info: {
                id: 3499,
                advert_id: "7246301442494103607",
                user_id: "3642056016410728",
                item_id: "0",
                item_type: 14,
                platform: 2608,
                layout: 1,
                position: 5,
                advert_type: 1,
                station_type: 0,
                author_name: "吃果冻不吐果冻皮",
                author_id: "3642056016410728",
                title: "大模型分布式训练并行技术（二）-数据并行",
                brief: "本文为分布式训练并行技术的第二篇：数据并行。由于其原理相对比较简单，因此，在日常会应用中用的比较多。",
                url: "https://juejin.cn/post/7254001262646738981",
                picture: "https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/10baed7e3e7b4203b98f16ad53f5b3c8~tplv-k3u1fbpfcp-watermark.image?",
                avatar: "https://p3-passport.byteacctimg.com/img/user-avatar/badef2efcd963b3a57efd67246af373c~300x300.image",
                start_time: "0",
                end_time: "0",
                ctime: "1688973656",
                mtime: "1688973656",
                sale_count: 0,
                sale_price: 0,
                discount_rate: 0,
                digg_count: 0,
                comment_count: 0,
                topic: "",
                topic_id: "0",
                status: 1,
                author_is_logout: 0,
                item_user_info: {
                  user_id: "3642056016410728",
                  user_name: "吃果冻不吐果冻皮",
                  company: "",
                  job_title: "",
                  avatar_large: "https://p3-passport.byteacctimg.com/img/user-avatar/badef2efcd963b3a57efd67246af373c~300x300.image",
                  level: 0,
                  description: "",
                  followee_count: 0,
                  follower_count: 0,
                  post_article_count: 0,
                  digg_article_count: 0,
                  got_digg_count: 0,
                  got_view_count: 0,
                  post_shortmsg_count: 0,
                  digg_shortmsg_count: 0,
                  isfollowed: false,
                  favorable_author: 0,
                  power: 0,
                  study_point: 0,
                  university: null,
                  major: null,
                  student_status: 0,
                  select_event_count: 0,
                  select_online_course_count: 0,
                  identity: 0,
                  is_select_annual: false,
                  select_annual_rank: 0,
                  annual_list_type: 0,
                  extraMap: null,
                  is_logout: 0,
                  annual_info: null,
                  account_amount: 0,
                  user_growth_info: null,
                  is_vip: false,
                  become_author_days: 0,
                  collection_set_article_count: 0,
                  recommend_article_count_daily: 0,
                  article_collect_count_daily: 0,
                },
              },
            },
            {
              item_type: 2,
              item_info: {
                article_id: "7251501842985959485",
                article_info: {
                  article_id: "7251501842985959485",
                  user_id: "676954891882119",
                  category_id: "6809637772874219534",
                  tag_ids: [6809640419505209358, 6809640642101116936],
                  visible_level: 0,
                  link_url: "",
                  cover_image: "https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/2b0fc96f42ea4218852e02bdba590cad~tplv-k3u1fbpfcp-watermark.image?",
                  is_gfw: 0,
                  title: "无需API KEY，免费使用ChatGPT3.5/4，还能体验ChatGPT的越狱模式",
                  brief_content: "freegpt-webui开源项目，基于gpt4free提供的API，可以免费使用 ChatPGT3.5/4模型，还可以使用ChatGPT增强版-越狱模式 DAN 模式 和 Evil 模式。前端项目是",
                  is_english: 0,
                  is_original: 1,
                  user_index: 10.087265535139206,
                  original_type: 0,
                  original_author: "",
                  content: "",
                  ctime: "1688372651",
                  mtime: "1688971150",
                  rtime: "1688372656",
                  draft_id: "7251498367816400956",
                  view_count: 6549,
                  collect_count: 68,
                  digg_count: 22,
                  comment_count: 6,
                  hot_index: 355,
                  is_hot: 0,
                  rank_index: 0.44841216,
                  status: 2,
                  verify_status: 1,
                  audit_status: 2,
                  mark_content: "",
                  display_count: 0,
                  is_markdown: 1,
                  app_html_content: "",
                  version: 2,
                },
                author_user_info: {
                  user_id: "676954891882119",
                  user_name: "CoderMiner",
                  company: "",
                  job_title: "开发工程师",
                  avatar_large: "https://p26-passport.byteacctimg.com/img/user-avatar/05e560da86f44cb9c21d285d6f545f00~300x300.image",
                  level: 0,
                  description: "Vuejs,Reactjs,Android,Python,C#,Go,MongoDB,Flutter,微服务",
                  followee_count: 0,
                  follower_count: 0,
                  post_article_count: 0,
                  digg_article_count: 0,
                  got_digg_count: 0,
                  got_view_count: 0,
                  post_shortmsg_count: 0,
                  digg_shortmsg_count: 0,
                  isfollowed: false,
                  favorable_author: 0,
                  power: 0,
                  study_point: 0,
                  university: {
                    university_id: "0",
                    name: "",
                    logo: "",
                  },
                  major: {
                    major_id: "0",
                    parent_id: "0",
                    name: "",
                  },
                  student_status: 0,
                  select_event_count: 0,
                  select_online_course_count: 0,
                  identity: 0,
                  is_select_annual: false,
                  select_annual_rank: 0,
                  annual_list_type: 0,
                  extraMap: {},
                  is_logout: 0,
                  annual_info: [],
                  account_amount: 0,
                  user_growth_info: {
                    user_id: 0,
                    jpower: 0,
                    jscore: 0,
                    jpower_level: 0,
                    jscore_level: 0,
                    jscore_title: "",
                    author_achievement_list: [],
                    vip_level: 0,
                    vip_title: "",
                    jscore_next_level_score: 0,
                    jscore_this_level_mini_score: 0,
                    vip_score: 0,
                  },
                  is_vip: false,
                  become_author_days: 0,
                  collection_set_article_count: 0,
                  recommend_article_count_daily: 0,
                  article_collect_count_daily: 0,
                },
                category: {
                  category_id: "0",
                  category_name: "",
                  category_url: "",
                  rank: 0,
                  back_ground: "",
                  icon: "",
                  show_type: 0,
                  item_type: 0,
                  promote_tag_cap: 0,
                  promote_priority: 0,
                },
                tags: [
                  {
                    id: 2546535,
                    tag_id: "6809640419505209358",
                    tag_name: "开源",
                    color: "#6EBD68",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/553ecacd498946a9a6d9.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1435972427,
                    mtime: 1688987882,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 9958,
                    concern_user_count: 245041,
                  },
                  {
                    id: 2546696,
                    tag_id: "6809640642101116936",
                    tag_name: "人工智能",
                    color: "#2e6cff",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/9b525117507d7a76c4ac.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 1,
                    ctime: 1472072600,
                    mtime: 1688993029,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 25765,
                    concern_user_count: 237134,
                  },
                ],
                user_interact: {
                  id: 7251501842985959485,
                  omitempty: 2,
                  user_id: 0,
                  is_digg: false,
                  is_follow: false,
                  is_collect: false,
                  collect_set_count: 0,
                },
                org: {
                  org_info: null,
                  is_followed: false,
                },
                req_id: "20230710205142F1EA693B02ADABADD4DB",
                status: {
                  push_status: 0,
                },
                extra: {
                  extra: "",
                },
              },
            },
            {
              item_type: 2,
              item_info: {
                article_id: "7211358106629750841",
                article_info: {
                  article_id: "7211358106629750841",
                  user_id: "2629687543097592",
                  category_id: "6809637767543259144",
                  tag_ids: [6809640407484334093, 6809640543006490638],
                  visible_level: 0,
                  link_url: "",
                  cover_image: "https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/649e5d7c4f974807abc0c53c7b0b8e86~tplv-k3u1fbpfcp-watermark.image?",
                  is_gfw: 0,
                  title: "🌝 重学 TS",
                  brief_content:
                    "非常汗颜，写ts好多年了，虽然不是anyscript风格，但一直当作类型标注在写，顶多用用函数重载和范型，连infer是谁都不认识，虽然也从当年这个文章中：用 TypeScript 类型运算实现一个中",
                  is_english: 0,
                  is_original: 1,
                  user_index: 9.53596847868568,
                  original_type: 0,
                  original_author: "",
                  content: "",
                  ctime: "1679035033",
                  mtime: "1679890525",
                  rtime: "1679043371",
                  draft_id: "7211357900294520869",
                  view_count: 54526,
                  collect_count: 2574,
                  digg_count: 1254,
                  comment_count: 105,
                  hot_index: 4085,
                  is_hot: 0,
                  rank_index: 0.13741392,
                  status: 2,
                  verify_status: 1,
                  audit_status: 2,
                  mark_content: "",
                  display_count: 0,
                  is_markdown: 1,
                  app_html_content: "",
                  version: 4,
                },
                author_user_info: {
                  user_id: "2629687543097592",
                  user_name: "支付宝体验科技",
                  company: "蚂蚁集团",
                  job_title: "",
                  avatar_large: "https://p3-passport.byteacctimg.com/img/user-avatar/72601134b1963ed58355921d5816ed25~300x300.image",
                  level: 0,
                  description: "探索极致用户体验与最佳工程实践",
                  followee_count: 0,
                  follower_count: 0,
                  post_article_count: 0,
                  digg_article_count: 0,
                  got_digg_count: 0,
                  got_view_count: 0,
                  post_shortmsg_count: 0,
                  digg_shortmsg_count: 0,
                  isfollowed: false,
                  favorable_author: 0,
                  power: 0,
                  study_point: 0,
                  university: {
                    university_id: "0",
                    name: "",
                    logo: "",
                  },
                  major: {
                    major_id: "0",
                    parent_id: "0",
                    name: "",
                  },
                  student_status: 0,
                  select_event_count: 0,
                  select_online_course_count: 0,
                  identity: 0,
                  is_select_annual: false,
                  select_annual_rank: 0,
                  annual_list_type: 0,
                  extraMap: {},
                  is_logout: 0,
                  annual_info: [],
                  account_amount: 0,
                  user_growth_info: {
                    user_id: 0,
                    jpower: 0,
                    jscore: 0,
                    jpower_level: 0,
                    jscore_level: 0,
                    jscore_title: "",
                    author_achievement_list: [],
                    vip_level: 0,
                    vip_title: "",
                    jscore_next_level_score: 0,
                    jscore_this_level_mini_score: 0,
                    vip_score: 0,
                  },
                  is_vip: false,
                  become_author_days: 0,
                  collection_set_article_count: 0,
                  recommend_article_count_daily: 0,
                  article_collect_count_daily: 0,
                },
                category: {
                  category_id: "0",
                  category_name: "",
                  category_url: "",
                  rank: 0,
                  back_ground: "",
                  icon: "",
                  show_type: 0,
                  item_type: 0,
                  promote_tag_cap: 0,
                  promote_priority: 0,
                },
                tags: [
                  {
                    id: 2546526,
                    tag_id: "6809640407484334093",
                    tag_name: "前端",
                    color: "#60ADFF",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/bac28828a49181c34110.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 1,
                    ctime: 1435971546,
                    mtime: 1688993283,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 389276,
                    concern_user_count: 655848,
                  },
                  {
                    id: 2546625,
                    tag_id: "6809640543006490638",
                    tag_name: "TypeScript",
                    color: "#0061c4",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/d788a559489fa6e30b25.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1441228068,
                    mtime: 1688992504,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 9556,
                    concern_user_count: 102572,
                  },
                ],
                user_interact: {
                  id: 7211358106629750841,
                  omitempty: 2,
                  user_id: 0,
                  is_digg: false,
                  is_follow: false,
                  is_collect: false,
                  collect_set_count: 0,
                },
                org: {
                  org_info: null,
                  is_followed: false,
                },
                req_id: "20230710205142F1EA693B02ADABADD4DB",
                status: {
                  push_status: 0,
                },
                extra: {
                  extra: "",
                },
              },
            },
            {
              item_type: 2,
              item_info: {
                article_id: "7232947178691444794",
                article_info: {
                  article_id: "7232947178691444794",
                  user_id: "4086244881751613",
                  category_id: "6809637767543259144",
                  tag_ids: [6809640407484334093, 6809640357354012685, 7147583745896218628],
                  visible_level: 0,
                  link_url: "",
                  cover_image: "",
                  is_gfw: 0,
                  title: "产品经理：客户想要个画板，你们前端能不能做？",
                  brief_content: "如果你用惯了process-on 和 drawio这类流程图工具，那么是时候试试白板了，发挥你的想象力，创造不一样的东西。",
                  is_english: 0,
                  is_original: 1,
                  user_index: 12.157203763403208,
                  original_type: 0,
                  original_author: "",
                  content: "",
                  ctime: "1684065814",
                  mtime: "1684117402",
                  rtime: "1684066463",
                  draft_id: "7231481633671495717",
                  view_count: 25889,
                  collect_count: 498,
                  digg_count: 285,
                  comment_count: 39,
                  hot_index: 1618,
                  is_hot: 0,
                  rank_index: 0.13637978,
                  status: 2,
                  verify_status: 1,
                  audit_status: 2,
                  mark_content: "",
                  display_count: 0,
                  is_markdown: 1,
                  app_html_content: "",
                  version: 2,
                },
                author_user_info: {
                  user_id: "4086244881751613",
                  user_name: "翔子丶",
                  company: "QMP",
                  job_title: "前端工程师",
                  avatar_large: "https://p6-passport.byteacctimg.com/img/user-avatar/8771fffda7a79c708fec62768f2df8ff~300x300.image",
                  level: 0,
                  description: "有志始知蓬莱近，无为总觉咫尺远",
                  followee_count: 0,
                  follower_count: 0,
                  post_article_count: 0,
                  digg_article_count: 0,
                  got_digg_count: 0,
                  got_view_count: 0,
                  post_shortmsg_count: 0,
                  digg_shortmsg_count: 0,
                  isfollowed: false,
                  favorable_author: 0,
                  power: 0,
                  study_point: 0,
                  university: {
                    university_id: "0",
                    name: "",
                    logo: "",
                  },
                  major: {
                    major_id: "0",
                    parent_id: "0",
                    name: "",
                  },
                  student_status: 0,
                  select_event_count: 0,
                  select_online_course_count: 0,
                  identity: 0,
                  is_select_annual: false,
                  select_annual_rank: 0,
                  annual_list_type: 0,
                  extraMap: {},
                  is_logout: 0,
                  annual_info: [],
                  account_amount: 0,
                  user_growth_info: {
                    user_id: 0,
                    jpower: 0,
                    jscore: 0,
                    jpower_level: 0,
                    jscore_level: 0,
                    jscore_title: "",
                    author_achievement_list: [],
                    vip_level: 0,
                    vip_title: "",
                    jscore_next_level_score: 0,
                    jscore_this_level_mini_score: 0,
                    vip_score: 0,
                  },
                  is_vip: false,
                  become_author_days: 0,
                  collection_set_article_count: 0,
                  recommend_article_count_daily: 0,
                  article_collect_count_daily: 0,
                },
                category: {
                  category_id: "0",
                  category_name: "",
                  category_url: "",
                  rank: 0,
                  back_ground: "",
                  icon: "",
                  show_type: 0,
                  item_type: 0,
                  promote_tag_cap: 0,
                  promote_priority: 0,
                },
                tags: [
                  {
                    id: 2546526,
                    tag_id: "6809640407484334093",
                    tag_name: "前端",
                    color: "#60ADFF",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/bac28828a49181c34110.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 1,
                    ctime: 1435971546,
                    mtime: 1688993283,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 389276,
                    concern_user_count: 655848,
                  },
                  {
                    id: 2546490,
                    tag_id: "6809640357354012685",
                    tag_name: "React.js",
                    color: "#61DAFB",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/f655215074250f10f8d4.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1432234367,
                    mtime: 1688992308,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 28200,
                    concern_user_count: 284947,
                  },
                  {
                    id: 4451642,
                    tag_id: "7147583745896218628",
                    tag_name: "掘金·日新计划",
                    color: "",
                    icon: "https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/2acbfd7dac7c40d7ab74f6aa55ee118c~tplv-k3u1fbpfcp-watermark.image?",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1664176524,
                    mtime: 1688988074,
                    id_type: 9,
                    tag_alias: "更文,更文挑战,10月更文,闯关,日新",
                    post_article_count: 35283,
                    concern_user_count: 8761,
                  },
                ],
                user_interact: {
                  id: 7232947178691444794,
                  omitempty: 2,
                  user_id: 0,
                  is_digg: false,
                  is_follow: false,
                  is_collect: false,
                  collect_set_count: 0,
                },
                org: {
                  org_info: null,
                  is_followed: false,
                },
                req_id: "20230710205142F1EA693B02ADABADD4DB",
                status: {
                  push_status: 0,
                },
                extra: {
                  extra: "",
                },
              },
            },
            {
              item_type: 2,
              item_info: {
                article_id: "7216769618705809469",
                article_info: {
                  article_id: "7216769618705809469",
                  user_id: "2714061017452557",
                  category_id: "6809637773935378440",
                  tag_ids: [7197380216015028281, 6809641073527226376],
                  visible_level: 0,
                  link_url: "",
                  cover_image: "https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/4c08c8606e4b4fb39d5c3eab3d90aec9~tplv-k3u1fbpfcp-watermark.image?",
                  is_gfw: 0,
                  title: "（建议收藏）ChatGPT 被锁中国区 ip ？别慌，看这篇ChatGPT \u0026 OpenAI 注册使用指北",
                  brief_content:
                    "大家好，我是祯民。最近这段时间随着 C 老师（Chatgpt) 的发布，仅仅是 chatgpt-3 的模型都有着让人吃惊的能力。我也试用了不短的时间，不管是编码的时候一些细节的咨询，还是学习时候的一些",
                  is_english: 0,
                  is_original: 1,
                  user_index: 10.218227520791467,
                  original_type: 0,
                  original_author: "",
                  content: "",
                  ctime: "1680318551",
                  mtime: "1681454636",
                  rtime: "1680848959",
                  draft_id: "7216703870684790842",
                  view_count: 56568,
                  collect_count: 488,
                  digg_count: 182,
                  comment_count: 147,
                  hot_index: 3157,
                  is_hot: 0,
                  rank_index: 0.13788363,
                  status: 2,
                  verify_status: 1,
                  audit_status: 2,
                  mark_content: "",
                  display_count: 0,
                  is_markdown: 1,
                  app_html_content: "",
                  version: 7,
                },
                author_user_info: {
                  user_id: "2714061017452557",
                  user_name: "祯民",
                  company: "字节跳动",
                  job_title: "前端开发工程师",
                  avatar_large: "https://p6-passport.byteacctimg.com/img/user-avatar/ed6a9fafe0ddf839c16b3e06859ecc5d~300x300.image",
                  level: 0,
                  description: "掘金小册《SSR实战：官网开发指南》、《前端自动化测试精讲》作者，公众号 - 祯民讲前端",
                  followee_count: 0,
                  follower_count: 0,
                  post_article_count: 0,
                  digg_article_count: 0,
                  got_digg_count: 0,
                  got_view_count: 0,
                  post_shortmsg_count: 0,
                  digg_shortmsg_count: 0,
                  isfollowed: false,
                  favorable_author: 0,
                  power: 0,
                  study_point: 0,
                  university: {
                    university_id: "0",
                    name: "",
                    logo: "",
                  },
                  major: {
                    major_id: "0",
                    parent_id: "0",
                    name: "",
                  },
                  student_status: 0,
                  select_event_count: 0,
                  select_online_course_count: 0,
                  identity: 0,
                  is_select_annual: false,
                  select_annual_rank: 0,
                  annual_list_type: 0,
                  extraMap: {},
                  is_logout: 0,
                  annual_info: [],
                  account_amount: 0,
                  user_growth_info: {
                    user_id: 0,
                    jpower: 0,
                    jscore: 0,
                    jpower_level: 0,
                    jscore_level: 0,
                    jscore_title: "",
                    author_achievement_list: [],
                    vip_level: 0,
                    vip_title: "",
                    jscore_next_level_score: 0,
                    jscore_this_level_mini_score: 0,
                    vip_score: 0,
                  },
                  is_vip: false,
                  become_author_days: 0,
                  collection_set_article_count: 0,
                  recommend_article_count_daily: 0,
                  article_collect_count_daily: 0,
                },
                category: {
                  category_id: "0",
                  category_name: "",
                  category_url: "",
                  rank: 0,
                  back_ground: "",
                  icon: "",
                  show_type: 0,
                  item_type: 0,
                  promote_tag_cap: 0,
                  promote_priority: 0,
                },
                tags: [
                  {
                    id: 4647111,
                    tag_id: "7197380216015028281",
                    tag_name: "ChatGPT",
                    color: "",
                    icon: "https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/1c332bcf15f9426e9bbbcca9edafe753~tplv-k3u1fbpfcp-watermark.image?",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1675770668,
                    mtime: 1688992308,
                    id_type: 9,
                    tag_alias: "ChatGPT,chatgpt",
                    post_article_count: 2749,
                    concern_user_count: 12266,
                  },
                  {
                    id: 2547008,
                    tag_id: "6809641073527226376",
                    tag_name: "OpenAI",
                    color: "",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/gold-ad-assets/1499837971464123784061e1a484792f8963f79cea8b7.jpg~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1499809199,
                    mtime: 1688990484,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 853,
                    concern_user_count: 6354,
                  },
                ],
                user_interact: {
                  id: 7216769618705809469,
                  omitempty: 2,
                  user_id: 0,
                  is_digg: false,
                  is_follow: false,
                  is_collect: false,
                  collect_set_count: 0,
                },
                org: {
                  org_info: null,
                  is_followed: false,
                },
                req_id: "20230710205142F1EA693B02ADABADD4DB",
                status: {
                  push_status: 0,
                },
                extra: {
                  extra: "",
                },
              },
            },
            {
              item_type: 2,
              item_info: {
                article_id: "7197070078360322109",
                article_info: {
                  article_id: "7197070078360322109",
                  user_id: "1574156383557255",
                  category_id: "6809637767543259144",
                  tag_ids: [6809640407484334093, 6809640408797167623],
                  visible_level: 0,
                  link_url: "",
                  cover_image: "https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/42e99d383d5a402f82222f0f0311995e~tplv-k3u1fbpfcp-watermark.image?",
                  is_gfw: 0,
                  title: "2023高频前端面试题合集之网络篇",
                  brief_content:
                    "近期整理了一下高频的前端面试题，分享给大家一起来学习。如有问题，欢迎指正！ 欢迎大家关注该专栏：点赞👍 + 收藏🤞 前端面试题系列文章： 【1】2022高频前端面试题——HTML篇 【2】2022高频",
                  is_english: 0,
                  is_original: 1,
                  user_index: 12.890385710336043,
                  original_type: 0,
                  original_author: "",
                  content: "",
                  ctime: "1675730308",
                  mtime: "1675731130",
                  rtime: "1675730315",
                  draft_id: "7196977951970869308",
                  view_count: 178035,
                  collect_count: 1575,
                  digg_count: 474,
                  comment_count: 33,
                  hot_index: 9408,
                  is_hot: 0,
                  rank_index: 0.2176403,
                  status: 2,
                  verify_status: 1,
                  audit_status: 2,
                  mark_content: "",
                  display_count: 0,
                  is_markdown: 1,
                  app_html_content: "",
                  version: 2,
                },
                author_user_info: {
                  user_id: "1574156383557255",
                  user_name: "法医",
                  company: "",
                  job_title: "🏆公众号@前端猎手",
                  avatar_large: "https://p26-passport.byteacctimg.com/img/user-avatar/ccf5b399305a43fb8c51d0ba1ee9cf31~300x300.image",
                  level: 0,
                  description: "我很荣幸成为一名前端开发者，我不是大神，但我正在为之努力！",
                  followee_count: 0,
                  follower_count: 0,
                  post_article_count: 0,
                  digg_article_count: 0,
                  got_digg_count: 0,
                  got_view_count: 0,
                  post_shortmsg_count: 0,
                  digg_shortmsg_count: 0,
                  isfollowed: false,
                  favorable_author: 0,
                  power: 0,
                  study_point: 0,
                  university: {
                    university_id: "0",
                    name: "",
                    logo: "",
                  },
                  major: {
                    major_id: "0",
                    parent_id: "0",
                    name: "",
                  },
                  student_status: 0,
                  select_event_count: 0,
                  select_online_course_count: 0,
                  identity: 0,
                  is_select_annual: false,
                  select_annual_rank: 0,
                  annual_list_type: 0,
                  extraMap: {},
                  is_logout: 0,
                  annual_info: [],
                  account_amount: 0,
                  user_growth_info: {
                    user_id: 0,
                    jpower: 0,
                    jscore: 0,
                    jpower_level: 0,
                    jscore_level: 0,
                    jscore_title: "",
                    author_achievement_list: [],
                    vip_level: 0,
                    vip_title: "",
                    jscore_next_level_score: 0,
                    jscore_this_level_mini_score: 0,
                    vip_score: 0,
                  },
                  is_vip: false,
                  become_author_days: 0,
                  collection_set_article_count: 0,
                  recommend_article_count_daily: 0,
                  article_collect_count_daily: 0,
                },
                category: {
                  category_id: "0",
                  category_name: "",
                  category_url: "",
                  rank: 0,
                  back_ground: "",
                  icon: "",
                  show_type: 0,
                  item_type: 0,
                  promote_tag_cap: 0,
                  promote_priority: 0,
                },
                tags: [
                  {
                    id: 2546526,
                    tag_id: "6809640407484334093",
                    tag_name: "前端",
                    color: "#60ADFF",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/bac28828a49181c34110.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 1,
                    ctime: 1435971546,
                    mtime: 1688993283,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 389276,
                    concern_user_count: 655848,
                  },
                  {
                    id: 2546527,
                    tag_id: "6809640408797167623",
                    tag_name: "后端",
                    color: "#C679FF",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/d83da9d012ddb7ae85f4.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 1,
                    ctime: 1435971556,
                    mtime: 1688993499,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 227524,
                    concern_user_count: 522587,
                  },
                ],
                user_interact: {
                  id: 7197070078360322109,
                  omitempty: 2,
                  user_id: 0,
                  is_digg: false,
                  is_follow: false,
                  is_collect: false,
                  collect_set_count: 0,
                },
                org: {
                  org_info: null,
                  is_followed: false,
                },
                req_id: "20230710205142F1EA693B02ADABADD4DB",
                status: {
                  push_status: 0,
                },
                extra: {
                  extra: "",
                },
              },
            },
            {
              item_type: 2,
              item_info: {
                article_id: "7239881176679448635",
                article_info: {
                  article_id: "7239881176679448635",
                  user_id: "3386151545092589",
                  category_id: "6809637769959178254",
                  tag_ids: [6809640407484334093, 6809640408797167623],
                  visible_level: 0,
                  link_url: "",
                  cover_image: "",
                  is_gfw: 0,
                  title: "前后端免费学 ｜ 第六届字节跳动青训营报名啦",
                  brief_content: "第六届字节跳动青训营来啦，这个暑假我们一起从学校走进职场、从萌新成长为高手。全程免费，期待与你共赴这场学习之旅~",
                  is_english: 0,
                  is_original: 1,
                  user_index: 14.141942911639608,
                  original_type: 0,
                  original_author: "",
                  content: "",
                  ctime: "1685672195",
                  mtime: "1687171745",
                  rtime: "1685689118",
                  draft_id: "7239554061279658040",
                  view_count: 25948,
                  collect_count: 62,
                  digg_count: 72,
                  comment_count: 30,
                  hot_index: 1398,
                  is_hot: 0,
                  rank_index: 0.19846443,
                  status: 2,
                  verify_status: 1,
                  audit_status: 2,
                  mark_content: "",
                  display_count: 0,
                  is_markdown: 1,
                  app_html_content: "",
                  version: 11,
                },
                author_user_info: {
                  user_id: "3386151545092589",
                  user_name: "青训营官方账号",
                  company: "北京字节跳动网络技术有限公司",
                  job_title: "研发",
                  avatar_large: "https://p6-passport.byteacctimg.com/img/user-avatar/de432cd6200bc3d3f7d633a3ccd528d8~300x300.image",
                  level: 0,
                  description: "我是青训营官方小助手，一个帮助大家学习成长的机器人~",
                  followee_count: 0,
                  follower_count: 0,
                  post_article_count: 0,
                  digg_article_count: 0,
                  got_digg_count: 0,
                  got_view_count: 0,
                  post_shortmsg_count: 0,
                  digg_shortmsg_count: 0,
                  isfollowed: false,
                  favorable_author: 0,
                  power: 0,
                  study_point: 0,
                  university: {
                    university_id: "0",
                    name: "",
                    logo: "",
                  },
                  major: {
                    major_id: "0",
                    parent_id: "0",
                    name: "",
                  },
                  student_status: 0,
                  select_event_count: 0,
                  select_online_course_count: 0,
                  identity: 0,
                  is_select_annual: false,
                  select_annual_rank: 0,
                  annual_list_type: 0,
                  extraMap: {},
                  is_logout: 0,
                  annual_info: [],
                  account_amount: 0,
                  user_growth_info: {
                    user_id: 0,
                    jpower: 0,
                    jscore: 0,
                    jpower_level: 0,
                    jscore_level: 0,
                    jscore_title: "",
                    author_achievement_list: [],
                    vip_level: 0,
                    vip_title: "",
                    jscore_next_level_score: 0,
                    jscore_this_level_mini_score: 0,
                    vip_score: 0,
                  },
                  is_vip: false,
                  become_author_days: 0,
                  collection_set_article_count: 0,
                  recommend_article_count_daily: 0,
                  article_collect_count_daily: 0,
                },
                category: {
                  category_id: "0",
                  category_name: "",
                  category_url: "",
                  rank: 0,
                  back_ground: "",
                  icon: "",
                  show_type: 0,
                  item_type: 0,
                  promote_tag_cap: 0,
                  promote_priority: 0,
                },
                tags: [
                  {
                    id: 2546526,
                    tag_id: "6809640407484334093",
                    tag_name: "前端",
                    color: "#60ADFF",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/bac28828a49181c34110.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 1,
                    ctime: 1435971546,
                    mtime: 1688993283,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 389276,
                    concern_user_count: 655848,
                  },
                  {
                    id: 2546527,
                    tag_id: "6809640408797167623",
                    tag_name: "后端",
                    color: "#C679FF",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/d83da9d012ddb7ae85f4.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 1,
                    ctime: 1435971556,
                    mtime: 1688993499,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 227524,
                    concern_user_count: 522587,
                  },
                ],
                user_interact: {
                  id: 7239881176679448635,
                  omitempty: 2,
                  user_id: 0,
                  is_digg: false,
                  is_follow: false,
                  is_collect: false,
                  collect_set_count: 0,
                },
                org: {
                  org_info: null,
                  is_followed: false,
                },
                req_id: "20230710205142F1EA693B02ADABADD4DB",
                status: {
                  push_status: 0,
                },
                extra: {
                  extra: "",
                },
              },
            },
            {
              item_type: 2,
              item_info: {
                article_id: "7253497745628889146",
                article_info: {
                  article_id: "7253497745628889146",
                  user_id: "642537280772456",
                  category_id: "6809637771511070734",
                  tag_ids: [6809640448827588622, 7197380216015028281, 6809640462614265863],
                  visible_level: 0,
                  link_url: "",
                  cover_image: "https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/182b0105175e4f3097e0a9f1a1c25fd7~tplv-k3u1fbpfcp-watermark.image?",
                  is_gfw: 0,
                  title: "AI写代码靠谱吗？",
                  brief_content:
                    "ChatGPT出来半年多了，用GPT编码的程序员有多少？虽然没有数据支撑，但我感觉用AI编码程序员并不多。我问过几个朋友，他们的回复是，AI没办法完成他想要完成的任务，最终还是得靠自己去写。",
                  is_english: 0,
                  is_original: 1,
                  user_index: 10.472472226001608,
                  original_type: 0,
                  original_author: "",
                  content: "",
                  ctime: "1688895712",
                  mtime: "1688895977",
                  rtime: "1688895720",
                  draft_id: "7250489084123349052",
                  view_count: 872,
                  collect_count: 1,
                  digg_count: 2,
                  comment_count: 2,
                  hot_index: 47,
                  is_hot: 0,
                  rank_index: 0.75219265,
                  status: 2,
                  verify_status: 1,
                  audit_status: 2,
                  mark_content: "",
                  display_count: 0,
                  is_markdown: 1,
                  app_html_content: "",
                  version: 2,
                },
                author_user_info: {
                  user_id: "642537280772456",
                  user_name: "石云升",
                  company: "公众号：石云升SYS",
                  job_title: "产品经理",
                  avatar_large: "https://p3-passport.byteacctimg.com/img/user-avatar/6c635cfd69c6df18e557000fe4719e2e~300x300.image",
                  level: 0,
                  description: "凡是过往，皆为序章。",
                  followee_count: 0,
                  follower_count: 0,
                  post_article_count: 0,
                  digg_article_count: 0,
                  got_digg_count: 0,
                  got_view_count: 0,
                  post_shortmsg_count: 0,
                  digg_shortmsg_count: 0,
                  isfollowed: false,
                  favorable_author: 0,
                  power: 0,
                  study_point: 0,
                  university: {
                    university_id: "0",
                    name: "",
                    logo: "",
                  },
                  major: {
                    major_id: "0",
                    parent_id: "0",
                    name: "",
                  },
                  student_status: 0,
                  select_event_count: 0,
                  select_online_course_count: 0,
                  identity: 0,
                  is_select_annual: false,
                  select_annual_rank: 0,
                  annual_list_type: 0,
                  extraMap: {},
                  is_logout: 0,
                  annual_info: [],
                  account_amount: 0,
                  user_growth_info: {
                    user_id: 0,
                    jpower: 0,
                    jscore: 0,
                    jpower_level: 0,
                    jscore_level: 0,
                    jscore_title: "",
                    author_achievement_list: [],
                    vip_level: 0,
                    vip_title: "",
                    jscore_next_level_score: 0,
                    jscore_this_level_mini_score: 0,
                    vip_score: 0,
                  },
                  is_vip: false,
                  become_author_days: 0,
                  collection_set_article_count: 0,
                  recommend_article_count_daily: 0,
                  article_collect_count_daily: 0,
                },
                category: {
                  category_id: "0",
                  category_name: "",
                  category_url: "",
                  rank: 0,
                  back_ground: "",
                  icon: "",
                  show_type: 0,
                  item_type: 0,
                  promote_tag_cap: 0,
                  promote_priority: 0,
                },
                tags: [
                  {
                    id: 2546556,
                    tag_id: "6809640448827588622",
                    tag_name: "Python",
                    color: "#356E9C",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/b51a1dacf9bb7883defe.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1436156327,
                    mtime: 1688992504,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 44000,
                    concern_user_count: 254846,
                  },
                  {
                    id: 4647111,
                    tag_id: "7197380216015028281",
                    tag_name: "ChatGPT",
                    color: "",
                    icon: "https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/1c332bcf15f9426e9bbbcca9edafe753~tplv-k3u1fbpfcp-watermark.image?",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1675770668,
                    mtime: 1688992308,
                    id_type: 9,
                    tag_alias: "ChatGPT,chatgpt",
                    post_article_count: 2749,
                    concern_user_count: 12266,
                  },
                  {
                    id: 2546566,
                    tag_id: "6809640462614265863",
                    tag_name: "产品经理",
                    color: "#616161",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/c763e6bb7d3443d2b2ae.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1436383520,
                    mtime: 1688979624,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 2917,
                    concern_user_count: 109211,
                  },
                ],
                user_interact: {
                  id: 7253497745628889146,
                  omitempty: 2,
                  user_id: 0,
                  is_digg: false,
                  is_follow: false,
                  is_collect: false,
                  collect_set_count: 0,
                },
                org: {
                  org_info: null,
                  is_followed: false,
                },
                req_id: "20230710205142F1EA693B02ADABADD4DB",
                status: {
                  push_status: 0,
                },
                extra: {
                  extra: "",
                },
              },
            },
            {
              item_type: 2,
              item_info: {
                article_id: "7253611796111654949",
                article_info: {
                  article_id: "7253611796111654949",
                  user_id: "1714893871914381",
                  category_id: "6809637767543259144",
                  tag_ids: [6809640407484334093, 6809640540305358862, 6809640398105870343],
                  visible_level: 0,
                  link_url: "",
                  cover_image: "",
                  is_gfw: 0,
                  title: "如何在页面关闭时发送 API 请求",
                  brief_content: "借助 navigator.sendBeacon、fetch keepalive 实现页面关闭时发送数据到服务器。在一些需求背景下，我们需要在页面销毁（关闭/刷新）时将数据同步给后台，比如 记录视频播放",
                  is_english: 0,
                  is_original: 1,
                  user_index: 10.681462074552083,
                  original_type: 0,
                  original_author: "",
                  content: "",
                  ctime: "1688899090",
                  mtime: "1688952053",
                  rtime: "1688899095",
                  draft_id: "7253391363453141050",
                  view_count: 1212,
                  collect_count: 17,
                  digg_count: 5,
                  comment_count: 1,
                  hot_index: 66,
                  is_hot: 0,
                  rank_index: 1.04887963,
                  status: 2,
                  verify_status: 1,
                  audit_status: 2,
                  mark_content: "",
                  display_count: 0,
                  is_markdown: 1,
                  app_html_content: "",
                  version: 3,
                },
                author_user_info: {
                  user_id: "1714893871914381",
                  user_name: "明里人",
                  company: "",
                  job_title: "@前端工程师",
                  avatar_large: "https://p6-passport.byteacctimg.com/img/user-avatar/e71d3789cc143bee211bfc02516920ab~300x300.image",
                  level: 0,
                  description: "严于律己，宽以待人。",
                  followee_count: 0,
                  follower_count: 0,
                  post_article_count: 0,
                  digg_article_count: 0,
                  got_digg_count: 0,
                  got_view_count: 0,
                  post_shortmsg_count: 0,
                  digg_shortmsg_count: 0,
                  isfollowed: false,
                  favorable_author: 0,
                  power: 0,
                  study_point: 0,
                  university: {
                    university_id: "0",
                    name: "",
                    logo: "",
                  },
                  major: {
                    major_id: "0",
                    parent_id: "0",
                    name: "",
                  },
                  student_status: 0,
                  select_event_count: 0,
                  select_online_course_count: 0,
                  identity: 0,
                  is_select_annual: false,
                  select_annual_rank: 0,
                  annual_list_type: 0,
                  extraMap: {},
                  is_logout: 0,
                  annual_info: [],
                  account_amount: 0,
                  user_growth_info: {
                    user_id: 0,
                    jpower: 0,
                    jscore: 0,
                    jpower_level: 0,
                    jscore_level: 0,
                    jscore_title: "",
                    author_achievement_list: [],
                    vip_level: 0,
                    vip_title: "",
                    jscore_next_level_score: 0,
                    jscore_this_level_mini_score: 0,
                    vip_score: 0,
                  },
                  is_vip: false,
                  become_author_days: 0,
                  collection_set_article_count: 0,
                  recommend_article_count_daily: 0,
                  article_collect_count_daily: 0,
                },
                category: {
                  category_id: "0",
                  category_name: "",
                  category_url: "",
                  rank: 0,
                  back_ground: "",
                  icon: "",
                  show_type: 0,
                  item_type: 0,
                  promote_tag_cap: 0,
                  promote_priority: 0,
                },
                tags: [
                  {
                    id: 2546526,
                    tag_id: "6809640407484334093",
                    tag_name: "前端",
                    color: "#60ADFF",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/bac28828a49181c34110.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 1,
                    ctime: 1435971546,
                    mtime: 1688993283,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 389276,
                    concern_user_count: 655848,
                  },
                  {
                    id: 2546623,
                    tag_id: "6809640540305358862",
                    tag_name: "HTTP",
                    color: "#616161",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/936251cc1634d8d98959.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1441226632,
                    mtime: 1688989391,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 6678,
                    concern_user_count: 205757,
                  },
                  {
                    id: 2546519,
                    tag_id: "6809640398105870343",
                    tag_name: "JavaScript",
                    color: "#616161",
                    icon: "https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/leancloud-assets/5d70fd6af940df373834.png~tplv-t2oaga2asx-image.image",
                    back_ground: "",
                    show_navi: 0,
                    ctime: 1435884803,
                    mtime: 1688993283,
                    id_type: 9,
                    tag_alias: "",
                    post_article_count: 130546,
                    concern_user_count: 514768,
                  },
                ],
                user_interact: {
                  id: 7253611796111654949,
                  omitempty: 2,
                  user_id: 0,
                  is_digg: false,
                  is_follow: false,
                  is_collect: false,
                  collect_set_count: 0,
                },
                org: {
                  org_info: null,
                  is_followed: false,
                },
                req_id: "20230710205142F1EA693B02ADABADD4DB",
                status: {
                  push_status: 0,
                },
                extra: {
                  extra: "",
                },
              },
            },
          ],
          cursor: "1",
          count: 1000,
          has_more: true,
        },
      },
    ];
    return mockApiList;
  },
});

window.addEventListener("DOMContentLoaded", () => {
  console.log("页面 dom 加载完毕");
});

const open = window.open;
window.open = (strUrl, strWindowName, strWindowFeatures) => {
  alert(strWindowName == "_top" ? "_blank" : strWindowName);
  console.log("复写window.open");
  open(strUrl, strWindowName == "_top" ? "_blank" : strWindowName, strWindowFeatures);
};
